// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe3ouPiOPWq9GiSYyBh4mQrDLZjWHdC_s',
    appId: '1:337411411982:web:696e2e5d9f77457066ac5f',
    messagingSenderId: '337411411982',
    projectId: 'chatapp-8c5ab',
    authDomain: 'chatapp-8c5ab.firebaseapp.com',
    storageBucket: 'chatapp-8c5ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe5PVSXGggR9LWrtU9Wrs2WmahQl_hgqQ',
    appId: '1:337411411982:android:24cfeff5a7e011c366ac5f',
    messagingSenderId: '337411411982',
    projectId: 'chatapp-8c5ab',
    storageBucket: 'chatapp-8c5ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGRDOFuUuRT4BG6oakaqdM19OautYWuOs',
    appId: '1:337411411982:ios:7e6070da6ea9323566ac5f',
    messagingSenderId: '337411411982',
    projectId: 'chatapp-8c5ab',
    storageBucket: 'chatapp-8c5ab.appspot.com',
    iosBundleId: 'com.example.chatApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGRDOFuUuRT4BG6oakaqdM19OautYWuOs',
    appId: '1:337411411982:ios:250e97e2d2b0c86066ac5f',
    messagingSenderId: '337411411982',
    projectId: 'chatapp-8c5ab',
    storageBucket: 'chatapp-8c5ab.appspot.com',
    iosBundleId: 'com.example.chatApp1.RunnerTests',
  );
}
