// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvJ4qjn1V5ZIPzqrbK_7vsz_wqboYD7qU',
    appId: '1:735939026473:web:2f9ddd8907a549732c0638',
    messagingSenderId: '735939026473',
    projectId: 'courseflu',
    authDomain: 'courseflu.firebaseapp.com',
    storageBucket: 'courseflu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRuWqcA-L3iVjCF53im1CFmsKjYOmIOaA',
    appId: '1:735939026473:android:119945f7c6cf39d42c0638',
    messagingSenderId: '735939026473',
    projectId: 'courseflu',
    storageBucket: 'courseflu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNp8aa60OUumtKdMFamLhzRIodIW8ve14',
    appId: '1:735939026473:ios:5ff9e4804c300e5d2c0638',
    messagingSenderId: '735939026473',
    projectId: 'courseflu',
    storageBucket: 'courseflu.appspot.com',
    iosBundleId: 'com.example.chatApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNp8aa60OUumtKdMFamLhzRIodIW8ve14',
    appId: '1:735939026473:ios:7f6b5aea3af0f6592c0638',
    messagingSenderId: '735939026473',
    projectId: 'courseflu',
    storageBucket: 'courseflu.appspot.com',
    iosBundleId: 'com.example.chatApp1.RunnerTests',
  );
}
